// Validate every DAX reference measure against the model using the app's engine, then emit frontend/src/lib/daxTrack.js
import fs from "fs"; import path from "path"; import { fileURLToPath } from "url";
const here = path.dirname(fileURLToPath(import.meta.url));
fs.copyFileSync(path.join(here, "..", "frontend", "src", "lib", "daxEngine.js"), path.join(here, ".dax.mjs"));
const { evaluateMeasure } = await import("./.dax.mjs");
const DIFF = { easy: "beginner", medium: "intermediate", hard: "advanced" };
const model = JSON.parse(fs.readFileSync(path.join(here, "dax", "model.json")));
let qs = [], bad = 0; const seen = new Set();
for (const f of fs.readdirSync(path.join(here, "dax")).filter((x) => /^questions_.*\.json$/.test(x)).sort()) {
  for (const q of JSON.parse(fs.readFileSync(path.join(here, "dax", f)))) {
    if (seen.has(q.id)) throw new Error("dup " + q.id); seen.add(q.id);
    const r = evaluateMeasure(q.answer, model);
    if (r.error) { console.log("ERR", q.id, q.answer, "->", r.error); bad++; }
    qs.push({ id: q.id, difficulty: DIFF[q.tier], topic: q.topic, title: q.title, context: q.context, task: q.task, hint: q.hint, answer: q.answer, solution: q.answer, starter: q.starter || "", expected: r.error ? null : r });
  }
}
const tiers = {}; qs.forEach((q) => (tiers[q.difficulty] = (tiers[q.difficulty] || 0) + 1));
console.log(`DAX: ${qs.length} questions`, tiers, `problems=${bad}`);
if (bad) process.exit(1);
// ship the model tables preview-safe (row cap for the big Date table handled in the page)
const out = { ...model, questions: qs };
fs.writeFileSync(path.join(here, "..", "frontend", "src", "lib", "daxTrack.js"), `/** DAX hands-on track: model + questions. GENERATED by powerbi-bank/build.mjs. */\nexport const DAX_MODEL = ${JSON.stringify(out)};\n`);
fs.unlinkSync(path.join(here, ".dax.mjs"));
console.log("wrote frontend/src/lib/daxTrack.js");
