"""Shared tooling: validate a company's questions against its seed, and emit frontend/src/lib/companies/<key>.js"""
import json, sqlite3, sys, os
HERE=os.path.dirname(os.path.abspath(__file__))
def q(v): return "NULL" if v is None else ("'"+v.replace("'","''")+"'" if isinstance(v,str) else str(v))
def build_sql(tables):
    out=[]
    for t in tables:
        cols=", ".join(f"{c['name']} {c['type']}"+(" PRIMARY KEY" if c.get('tag')=='PK' else "") for c in t['columns'])
        out.append(f"CREATE TABLE {t['name']} ({cols});")
        for r in t['rows']: out.append(f"INSERT INTO {t['name']} VALUES ({','.join(q(v) for v in r)});")
    return "\n".join(out)
DIFF={'easy':'beginner','medium':'intermediate','hard':'advanced'}
def emit(company, tables, questions_compact, outdir=None):
    db=sqlite3.connect(':memory:'); db.executescript(build_sql(tables))
    qs=[]; bad=0; seen=set()
    for c in questions_compact:
        assert c['id'] not in seen, 'dup '+c['id']; seen.add(c['id'])
        try:
            cur=db.execute(c['answer']); cols=[d[0] for d in cur.description]; rows=cur.fetchall()
            if not rows: print('EMPTY',c['id']); bad+=1
        except Exception as e: print('ERR',c['id'],e); bad+=1; cols=[]
        qs.append({'id':c['id'],'difficulty':DIFF[c['tier']],'title':c['title'],'context':c['context'],'task':c['task'],
                   'output':', '.join(cols),'rules':c.get('rules',c['hint'])+(' Row order must match the task.' if c.get('order') else ''),
                   'answer':c['answer'],'hint':c['hint'],'solution':c['answer'],'topic':c['topic']})
    tiers={t:sum(1 for c in questions_compact if c['tier']==t) for t in DIFF}
    print(f"{company['name']}: {len(qs)} questions {tiers}; rows={sum(len(t['rows']) for t in tables)}; problems={bad}")
    if bad: sys.exit(1)
    obj={**company,'tables':tables,'questions':qs}
    outdir=outdir or os.path.join(HERE,'..','frontend','src','lib','companies'); os.makedirs(outdir,exist_ok=True)
    path=os.path.join(outdir,company['key']+'.js')
    open(path,'w').write(f"/** {company['name']} schema + question track. GENERATED by sql-bank/{company['key']}/build.py — edit the bank and rebuild. */\nexport const {company['key'].upper()} = "+json.dumps(obj,ensure_ascii=False,separators=(',',':'))+";\n")
    print('wrote',os.path.relpath(path,HERE))
