// Validates every Excel answer against its workbook using the app's own engine, then writes frontend/src/lib/excelTrack.js
// Layout: excel-bank/<key>/workbook.json + questions_*.json  (one folder per workbook)
import fs from "fs"; import path from "path"; import { fileURLToPath } from "url";
const here = path.dirname(fileURLToPath(import.meta.url));
fs.copyFileSync(path.join(here, "..", "frontend", "src", "lib", "excelEngine.js"), path.join(here, ".engine.mjs"));
const { evaluate, buildSheet } = await import("./.engine.mjs");
const DIFF = { easy: "beginner", medium: "intermediate", hard: "advanced" };
const out = []; let bad = 0; const seen = new Set();
for (const dir of fs.readdirSync(here).filter((d) => fs.existsSync(path.join(here, d, "workbook.json"))).sort((a, b) => ["sales","hr","inventory","marketing","finance"].indexOf(a) - ["sales","hr","inventory","marketing","finance"].indexOf(b))) {
  const wb = JSON.parse(fs.readFileSync(path.join(here, dir, "workbook.json")));
  const sheet = buildSheet(wb.tables); const qs = [];
  for (const f of fs.readdirSync(path.join(here, dir)).filter((x) => /^questions_.*\.json$/.test(x)).sort()) {
    for (const q of JSON.parse(fs.readFileSync(path.join(here, dir, f)))) {
      if (seen.has(q.id)) throw new Error("dup " + q.id); seen.add(q.id);
      const r = evaluate(q.answer, sheet);
      if (r.error) { console.log("ERR", q.id, q.answer, "->", r.error); bad++; }
      qs.push({ id: q.id, difficulty: DIFF[q.tier], topic: q.topic, title: q.title, context: q.context, task: q.task, hint: q.hint, answer: q.answer, solution: q.answer, expected: r.error ? null : r.value });
    }
  }
  const tiers = {}; qs.forEach((q) => (tiers[q.difficulty] = (tiers[q.difficulty] || 0) + 1));
  console.log(`${wb.name}: ${qs.length} questions`, tiers, `problems=${bad}`);
  out.push({ ...wb, questions: qs });
}
if (bad) process.exit(1);
fs.writeFileSync(path.join(here, "..", "frontend", "src", "lib", "excelTrack.js"), `/** Excel track: workbooks + questions. GENERATED by excel-bank/build.mjs — edit the bank and rebuild. */\nexport const EXCEL_WORKBOOKS = ${JSON.stringify(out)};\n`);
fs.unlinkSync(path.join(here, ".engine.mjs"));
console.log("wrote frontend/src/lib/excelTrack.js —", out.length, "workbooks,", out.reduce((n, w) => n + w.questions.length, 0), "questions");
