// Convert _generated.json into the app's MCQ shape and write frontend/src/lib/powerbiConcepts.js
import fs from "fs"; import path from "path"; import { fileURLToPath } from "url";
const here = path.dirname(fileURLToPath(import.meta.url));
const raw = JSON.parse(fs.readFileSync(path.join(here, "_generated.json")));
const DIFF = { easy: "beginner", medium: "intermediate", hard: "advanced" };
const perTier = {}; const out = [];
raw.forEach((r) => {
  const d = DIFF[r.tier]; perTier[d] = (perTier[d] || 0) + 1;
  out.push({ id: `powerbi-${r.tier[0]}-c${perTier[d]}`, module: "powerbi", difficulty: d, type: "mcq", topic: r.topic, title: r.title, prompt: r.q, options: r.options, answer: r.answer, hint: r.topic, solution: r.why });
});
const tiers = {}; out.forEach((q) => (tiers[q.difficulty] = (tiers[q.difficulty] || 0) + 1));
fs.writeFileSync(path.join(here, "..", "..", "frontend", "src", "lib", "powerbiConcepts.js"), `/** Power BI concept MCQs — GENERATED by powerbi-bank/concepts/build.mjs. */\nexport const POWERBI_CONCEPTS = ${JSON.stringify(out)};\n`);
console.log("wrote powerbiConcepts.js —", out.length, "questions", tiers);
