"""Validate every Python reference solution by running it (CPython + pandas) against its dataset, then emit frontend/src/lib/pythonTrack.js.
Layout: python-bank/<key>/dataset.json + questions_*.json. Each question's answer must assign `result`."""
import json, os, sys, io, glob, traceback, contextlib
here=os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, here); from grader import canon
import pandas as pd, numpy as np
DIFF={'easy':'beginner','medium':'intermediate','hard':'advanced'}
PRELUDE = "import pandas as pd, numpy as np, math, re, json, datetime, collections, itertools, statistics\nfrom collections import Counter, defaultdict\n"
def load_frames(ds):
    g={}
    for name,csv_text in ds['frames'].items():
        df=pd.read_csv(io.StringIO(csv_text))
        for c in df.columns:
            if c.endswith('_date') or c in ('order_date','signup_date','review_date','month','watch_date','start_date','hire_date','exit_date'): df[c]=pd.to_datetime(df[c], errors='coerce')
        g[name]=df
    return g
def run(code, frames):
    g={'__name__':'__main__'}; exec(PRELUDE, g); g.update({k:v.copy() for k,v in frames.items()})
    out=io.StringIO()
    with contextlib.redirect_stdout(out): exec(code, g)
    if 'result' not in g: raise RuntimeError("solution did not assign `result`")
    return canon(g['result']), out.getvalue()
out=[]; bad=0; seen=set()
for d in sorted([x for x in os.listdir(here) if os.path.exists(os.path.join(here,x,'dataset.json'))]):
    ds=json.load(open(os.path.join(here,d,'dataset.json'))); frames=load_frames(ds); qs=[]
    for f in sorted(glob.glob(os.path.join(here,d,'questions_*.json'))):
        for q in json.load(open(f)):
            assert q['id'] not in seen, 'dup '+q['id']; seen.add(q['id'])
            try:
                expected,_=run(q['answer'], frames)
                if expected['kind']=='df' and not expected['rows']: print('EMPTY', q['id']); bad+=1
                if expected['kind']=='series' and not expected['values']: print('EMPTY', q['id']); bad+=1
            except Exception as e:
                print('ERR', q['id'], type(e).__name__, str(e)[:120]); bad+=1; expected=None
            qs.append({'id':q['id'],'difficulty':DIFF[q['tier']],'topic':q['topic'],'title':q['title'],'context':q['context'],'task':q['task'],'hint':q['hint'],'answer':q['answer'],'solution':q['answer'],'starter':q.get('starter',''),'order':bool(q.get('order')),'expected':expected})
    tiers={}
    for q in qs: tiers[q['difficulty']]=tiers.get(q['difficulty'],0)+1
    print(f"{ds['name']}: {len(qs)} questions {tiers} problems={bad}")
    out.append({**ds,'questions':qs})
if bad: sys.exit(1)
grader_src=open(os.path.join(here,'grader.py')).read()
js="/** Python track: datasets + questions. GENERATED by python-bank/build.py — edit the bank and rebuild. */\nexport const PYTHON_PRELUDE = "+json.dumps(PRELUDE)+";\nexport const PYTHON_GRADER = "+json.dumps(grader_src)+";\nexport const PYTHON_DATASETS = "+json.dumps(out)+";\n"
open(os.path.join(here,'..','frontend','src','lib','pythonTrack.js'),'w').write(js)
print('wrote frontend/src/lib/pythonTrack.js —', len(out), 'datasets,', sum(len(x['questions']) for x in out), 'questions')
