// Seed question bank — ~25 free questions per module (mix of difficulties).
// Each additional locked question is represented as a placeholder for the lock UI.

export const MODULES = [
  { key: "excel", name: "Excel", tagline: "Formulas, PivotTables & Power Query", icon: "Sheet", accent: "#00FF88", total: 1000 },
  { key: "sql", name: "SQL", tagline: "Query real data with SQLite in-browser", icon: "Database", accent: "#00D4FF", total: 1000 },
  { key: "python", name: "Python", tagline: "Pandas, NumPy & Data Cleaning", icon: "Code2", accent: "#FFD166", total: 1000 },
  { key: "powerbi", name: "Power BI", tagline: "DAX, Data Modeling & Dashboards", icon: "BarChart3", accent: "#F58549", total: 1000 },
  { key: "stats", name: "Statistics", tagline: "Distributions, Tests & Regression", icon: "Sigma", accent: "#B892FF", total: 1000 },
];

// helper to build ids
const q = (module, idx, difficulty, obj) => ({
  id: `${module}-${difficulty[0]}-${idx}`,
  module, difficulty, ...obj,
});

// ---------- EXCEL ----------
export const excelQuestions = [
  // BEGINNER (9)
  q("excel", 1, "beginner", { type: "fill", title: "SUM a column", prompt: "Write a formula to add all numbers in cells A1:A10.", answer: "=SUM(A1:A10)", hint: "Use the SUM function with a range.", solution: "=SUM(A1:A10) returns the total of A1 through A10." }),
  q("excel", 2, "beginner", { type: "fill", title: "Average of a range", prompt: "Return the average of B2:B20.", answer: "=AVERAGE(B2:B20)", hint: "Use AVERAGE(range).", solution: "=AVERAGE(B2:B20)" }),
  q("excel", 3, "beginner", { type: "fill", title: "COUNT numeric cells", prompt: "Count how many numeric values are in C1:C50.", answer: "=COUNT(C1:C50)", hint: "COUNT ignores text; use COUNTA for text too.", solution: "=COUNT(C1:C50)" }),
  q("excel", 4, "beginner", { type: "mcq", title: "Absolute reference", prompt: "Which reference is absolute?", options: ["A1", "$A1", "A$1", "$A$1"], answer: "$A$1", hint: "Absolute locks both row and column.", solution: "$A$1 locks both row and column when copied." }),
  q("excel", 5, "beginner", { type: "fill", title: "MAX value", prompt: "Return the largest value in D1:D100.", answer: "=MAX(D1:D100)", hint: "Use MAX.", solution: "=MAX(D1:D100)" }),
  q("excel", 6, "beginner", { type: "fill", title: "Simple IF", prompt: "If A1 > 50, return 'Pass' else 'Fail'.", answer: '=IF(A1>50,"Pass","Fail")', hint: "IF(condition, value_if_true, value_if_false)", solution: '=IF(A1>50,"Pass","Fail")' }),
  q("excel", 7, "beginner", { type: "mcq", title: "Freeze first row", prompt: "Which menu freezes the top row?", options: ["Data > Filter", "View > Freeze Panes", "Home > Format", "Insert > Table"], answer: "View > Freeze Panes", hint: "It's under View.", solution: "View > Freeze Panes > Freeze Top Row." }),
  q("excel", 8, "beginner", { type: "fill", title: "Concatenate names", prompt: "Join A1 and B1 with a space between them.", answer: '=A1&" "&B1', hint: "Use & or CONCAT.", solution: '=A1&" "&B1 or =CONCAT(A1," ",B1)' }),
  q("excel", 9, "beginner", { type: "fill", title: "LEN of a string", prompt: "Return character length of text in A2.", answer: "=LEN(A2)", hint: "LEN gives length.", solution: "=LEN(A2)" }),
  // INTERMEDIATE (9)
  q("excel", 10, "intermediate", { type: "fill", title: "VLOOKUP exact match", prompt: "Lookup ID in A2 from table F2:H100, return 3rd column, exact match.", answer: "=VLOOKUP(A2,F2:H100,3,FALSE)", hint: "4th arg FALSE = exact match.", solution: "=VLOOKUP(A2,F2:H100,3,FALSE)" }),
  q("excel", 11, "intermediate", { type: "fill", title: "SUMIF single criterion", prompt: "Sum values in B2:B100 where A2:A100 = \"Sales\".", answer: '=SUMIF(A2:A100,"Sales",B2:B100)', hint: "SUMIF(range, criteria, sum_range)", solution: '=SUMIF(A2:A100,"Sales",B2:B100)' }),
  q("excel", 12, "intermediate", { type: "fill", title: "COUNTIFS multiple", prompt: 'Count rows where region="APAC" and amount>1000.', answer: '=COUNTIFS(A:A,"APAC",B:B,">1000")', hint: "Use COUNTIFS.", solution: '=COUNTIFS(A:A,"APAC",B:B,">1000")' }),
  q("excel", 13, "intermediate", { type: "mcq", title: "XLOOKUP vs VLOOKUP", prompt: "XLOOKUP is preferred because…", options: ["It only works with numbers", "It can search left of the lookup column", "It requires sorted data", "It's slower than VLOOKUP"], answer: "It can search left of the lookup column", hint: "Directionality.", solution: "XLOOKUP can search in both directions and returns arrays." }),
  q("excel", 14, "intermediate", { type: "fill", title: "IFERROR wrap", prompt: "Wrap a VLOOKUP so if not found returns \"N/A\".", answer: '=IFERROR(VLOOKUP(A2,F:H,3,FALSE),"N/A")', hint: "IFERROR(value, value_if_error).", solution: '=IFERROR(VLOOKUP(A2,F:H,3,FALSE),"N/A")' }),
  q("excel", 15, "intermediate", { type: "fill", title: "TRIM text", prompt: "Remove leading and trailing spaces from A1.", answer: "=TRIM(A1)", hint: "TRIM is your friend.", solution: "=TRIM(A1)" }),
  q("excel", 16, "intermediate", { type: "mcq", title: "PivotTable value area", prompt: "Which area shows the aggregated numbers?", options: ["Filters", "Columns", "Rows", "Values"], answer: "Values", hint: "The name is a hint.", solution: "Values area contains SUM/COUNT/AVG etc." }),
  q("excel", 17, "intermediate", { type: "fill", title: "AVERAGEIFS", prompt: "Average amounts where region=\"EU\" and month=\"Jan\".", answer: '=AVERAGEIFS(B:B,C:C,"EU",D:D,"Jan")', hint: "AVERAGEIFS(avg_range, criteria_range1, criteria1, ...)", solution: '=AVERAGEIFS(B:B,C:C,"EU",D:D,"Jan")' }),
  q("excel", 18, "intermediate", { type: "fill", title: "Nested IF", prompt: "Grade: >=90 A, >=75 B, else C. Cell A1.", answer: '=IF(A1>=90,"A",IF(A1>=75,"B","C"))', hint: "Nest IFs left to right.", solution: '=IF(A1>=90,"A",IF(A1>=75,"B","C"))' }),
  // ADVANCED (7)
  q("excel", 19, "advanced", { type: "fill", title: "INDEX MATCH", prompt: "Look up A2 in F:F, return matching value from H:H.", answer: "=INDEX(H:H,MATCH(A2,F:F,0))", hint: "MATCH gives position; INDEX fetches value.", solution: "=INDEX(H:H,MATCH(A2,F:F,0))" }),
  q("excel", 20, "advanced", { type: "fill", title: "Dynamic UNIQUE + SORT", prompt: "Return unique sorted values from A2:A100.", answer: "=SORT(UNIQUE(A2:A100))", hint: "Combine SORT and UNIQUE.", solution: "=SORT(UNIQUE(A2:A100))" }),
  q("excel", 21, "advanced", { type: "fill", title: "FILTER by criterion", prompt: "Filter A2:B100 where B >= 1000.", answer: "=FILTER(A2:B100,B2:B100>=1000)", hint: "FILTER(array, include).", solution: "=FILTER(A2:B100,B2:B100>=1000)" }),
  q("excel", 22, "advanced", { type: "mcq", title: "Power Query use", prompt: "Best for repeating ETL transformations?", options: ["Formulas", "VBA", "Power Query", "PivotTable"], answer: "Power Query", hint: "M language.", solution: "Power Query records ETL steps that refresh on load." }),
  q("excel", 23, "advanced", { type: "fill", title: "LAMBDA basics", prompt: "Define a LAMBDA that doubles a number, applied to A1.", answer: "=LAMBDA(x,x*2)(A1)", hint: "LAMBDA(params, expr)(args).", solution: "=LAMBDA(x,x*2)(A1)" }),
  q("excel", 24, "advanced", { type: "fill", title: "SEQUENCE", prompt: "Generate numbers 1 to 10 vertically.", answer: "=SEQUENCE(10)", hint: "SEQUENCE(rows).", solution: "=SEQUENCE(10)" }),
  q("excel", 25, "advanced", { type: "mcq", title: "Goal Seek", prompt: "Which is What-if analysis?", options: ["Filter", "Goal Seek", "Sort", "Format Cells"], answer: "Goal Seek", hint: "Data > What-If Analysis.", solution: "Goal Seek finds the input for a desired output." }),
];

// ---------- SQL ----------
// Sample DB shipped with SQL.js (employees, departments, sales, customers, orders)
export const SQL_SEED = `
CREATE TABLE employees (id INTEGER PRIMARY KEY, name TEXT, dept_id INTEGER, salary INTEGER, hire_date TEXT);
INSERT INTO employees VALUES (1,'Alice',1,90000,'2021-03-14'),(2,'Bob',2,75000,'2020-07-10'),(3,'Carol',1,120000,'2019-01-22'),(4,'David',3,68000,'2022-11-02'),(5,'Eve',2,95000,'2021-06-30'),(6,'Frank',3,110000,'2018-05-19'),(7,'Grace',1,50000,'2023-02-15'),(8,'Henry',2,82000,'2022-08-01');
CREATE TABLE departments (id INTEGER PRIMARY KEY, name TEXT);
INSERT INTO departments VALUES (1,'Engineering'),(2,'Sales'),(3,'Marketing');
CREATE TABLE customers (id INTEGER PRIMARY KEY, name TEXT, city TEXT, signup_date TEXT);
INSERT INTO customers VALUES (1,'Ravi','Mumbai','2023-01-05'),(2,'Priya','Delhi','2023-02-19'),(3,'Sam','Bengaluru','2023-03-11'),(4,'Meera','Chennai','2023-06-01'),(5,'Arjun','Pune','2024-01-08');
CREATE TABLE orders (id INTEGER PRIMARY KEY, customer_id INTEGER, amount INTEGER, order_date TEXT, status TEXT);
INSERT INTO orders VALUES (1,1,1200,'2024-01-10','delivered'),(2,1,540,'2024-02-01','delivered'),(3,2,999,'2024-01-15','cancelled'),(4,3,2500,'2024-02-20','delivered'),(5,3,300,'2024-03-05','pending'),(6,4,7800,'2024-01-25','delivered'),(7,5,120,'2024-03-11','delivered'),(8,2,600,'2024-04-02','delivered'),(9,4,450,'2024-04-15','pending'),(10,1,3200,'2024-05-01','delivered');
CREATE TABLE sales (id INTEGER PRIMARY KEY, region TEXT, product TEXT, amount INTEGER, sale_date TEXT);
INSERT INTO sales VALUES (1,'North','Widget',500,'2024-01-01'),(2,'South','Widget',700,'2024-01-05'),(3,'North','Gadget',1200,'2024-02-10'),(4,'East','Widget',450,'2024-02-15'),(5,'West','Gadget',900,'2024-03-01'),(6,'North','Doohickey',350,'2024-03-15'),(7,'South','Gadget',1100,'2024-04-01'),(8,'East','Doohickey',800,'2024-04-10');
`;

export const sqlQuestions = [
  // BEGINNER (9)
  q("sql", 1, "beginner", { type: "code", title: "All employees", prompt: "Select all rows from the employees table.", answer: "SELECT * FROM employees;", expectedRows: 8, hint: "SELECT * FROM table_name", solution: "SELECT * FROM employees;" }),
  q("sql", 2, "beginner", { type: "code", title: "Employees earning > 80k", prompt: "Names of employees with salary greater than 80000.", answer: "SELECT name FROM employees WHERE salary > 80000;", expectedRows: 5, hint: "Use WHERE.", solution: "SELECT name FROM employees WHERE salary > 80000;" }),
  q("sql", 3, "beginner", { type: "code", title: "Order by salary desc", prompt: "Top 3 highest paid employees (name, salary).", answer: "SELECT name, salary FROM employees ORDER BY salary DESC LIMIT 3;", expectedRows: 3, hint: "ORDER BY … DESC LIMIT 3", solution: "SELECT name, salary FROM employees ORDER BY salary DESC LIMIT 3;" }),
  q("sql", 4, "beginner", { type: "code", title: "Distinct cities", prompt: "List unique cities from customers.", answer: "SELECT DISTINCT city FROM customers;", expectedRows: 5, hint: "DISTINCT keyword.", solution: "SELECT DISTINCT city FROM customers;" }),
  q("sql", 5, "beginner", { type: "code", title: "Count employees", prompt: "How many employees are there?", answer: "SELECT COUNT(*) FROM employees;", expectedRows: 1, hint: "COUNT(*)", solution: "SELECT COUNT(*) FROM employees;" }),
  q("sql", 6, "beginner", { type: "code", title: "Delivered orders", prompt: "All order rows with status = 'delivered'.", answer: "SELECT * FROM orders WHERE status='delivered';", expectedRows: 7, hint: "WHERE status = 'delivered'", solution: "SELECT * FROM orders WHERE status = 'delivered';" }),
  q("sql", 7, "beginner", { type: "code", title: "Sum of order amounts", prompt: "Total amount across all orders.", answer: "SELECT SUM(amount) FROM orders;", expectedRows: 1, hint: "SUM aggregate.", solution: "SELECT SUM(amount) FROM orders;" }),
  q("sql", 8, "beginner", { type: "code", title: "Average salary", prompt: "Average salary of employees.", answer: "SELECT AVG(salary) FROM employees;", expectedRows: 1, hint: "AVG().", solution: "SELECT AVG(salary) FROM employees;" }),
  q("sql", 9, "beginner", { type: "code", title: "Customers from Mumbai", prompt: "Names of customers whose city is Mumbai.", answer: "SELECT name FROM customers WHERE city='Mumbai';", expectedRows: 1, hint: "WHERE city='Mumbai'.", solution: "SELECT name FROM customers WHERE city = 'Mumbai';" }),
  // INTERMEDIATE (9)
  q("sql", 10, "intermediate", { type: "code", title: "Group by department", prompt: "Average salary per department (dept_id, avg_salary).", answer: "SELECT dept_id, AVG(salary) FROM employees GROUP BY dept_id;", expectedRows: 3, hint: "GROUP BY dept_id.", solution: "SELECT dept_id, AVG(salary) as avg_salary FROM employees GROUP BY dept_id;" }),
  q("sql", 11, "intermediate", { type: "code", title: "Join employees + departments", prompt: "Show employee name and department name.", answer: "SELECT e.name, d.name FROM employees e JOIN departments d ON e.dept_id=d.id;", expectedRows: 8, hint: "INNER JOIN on dept_id.", solution: "SELECT e.name, d.name FROM employees e JOIN departments d ON e.dept_id = d.id;" }),
  q("sql", 12, "intermediate", { type: "code", title: "Customers with orders", prompt: "Customer name and total spend for delivered orders, per customer.", answer: "SELECT c.name, SUM(o.amount) FROM customers c JOIN orders o ON c.id=o.customer_id WHERE o.status='delivered' GROUP BY c.id;", expectedRows: 5, hint: "JOIN + GROUP BY.", solution: "SELECT c.name, SUM(o.amount) FROM customers c JOIN orders o ON c.id=o.customer_id WHERE o.status='delivered' GROUP BY c.id;" }),
  q("sql", 13, "intermediate", { type: "code", title: "HAVING clause", prompt: "Departments with average salary > 80000 (dept_id, avg).", answer: "SELECT dept_id, AVG(salary) FROM employees GROUP BY dept_id HAVING AVG(salary) > 80000;", expectedRows: 2, hint: "HAVING filters aggregates.", solution: "SELECT dept_id, AVG(salary) FROM employees GROUP BY dept_id HAVING AVG(salary) > 80000;" }),
  q("sql", 14, "intermediate", { type: "code", title: "CASE WHEN", prompt: "Show employee name and 'High' if salary>=90000 else 'Low'.", answer: "SELECT name, CASE WHEN salary>=90000 THEN 'High' ELSE 'Low' END FROM employees;", expectedRows: 8, hint: "CASE WHEN … THEN … ELSE … END.", solution: "SELECT name, CASE WHEN salary >= 90000 THEN 'High' ELSE 'Low' END AS tier FROM employees;" }),
  q("sql", 15, "intermediate", { type: "code", title: "LEFT JOIN customers", prompt: "All customers with count of their orders (may be zero).", answer: "SELECT c.name, COUNT(o.id) FROM customers c LEFT JOIN orders o ON o.customer_id=c.id GROUP BY c.id;", expectedRows: 5, hint: "LEFT JOIN preserves left side.", solution: "SELECT c.name, COUNT(o.id) FROM customers c LEFT JOIN orders o ON o.customer_id = c.id GROUP BY c.id;" }),
  q("sql", 16, "intermediate", { type: "code", title: "Subquery", prompt: "Employees earning more than the average salary.", answer: "SELECT name FROM employees WHERE salary > (SELECT AVG(salary) FROM employees);", expectedRows: 4, hint: "Nested SELECT.", solution: "SELECT name FROM employees WHERE salary > (SELECT AVG(salary) FROM employees);" }),
  q("sql", 17, "intermediate", { type: "code", title: "UNION", prompt: "List of names from both employees and customers.", answer: "SELECT name FROM employees UNION SELECT name FROM customers;", expectedRows: 13, hint: "UNION removes duplicates.", solution: "SELECT name FROM employees UNION SELECT name FROM customers;" }),
  q("sql", 18, "intermediate", { type: "code", title: "Region sales sum", prompt: "Total sales amount per region.", answer: "SELECT region, SUM(amount) FROM sales GROUP BY region;", expectedRows: 4, hint: "GROUP BY region.", solution: "SELECT region, SUM(amount) FROM sales GROUP BY region;" }),
  // ADVANCED (7)
  q("sql", 19, "advanced", { type: "code", title: "ROW_NUMBER by dept", prompt: "Rank employees by salary within each department.", answer: "SELECT name, dept_id, ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) FROM employees;", expectedRows: 8, hint: "Use ROW_NUMBER() OVER (PARTITION BY).", solution: "SELECT name, dept_id, ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rn FROM employees;" }),
  q("sql", 20, "advanced", { type: "code", title: "Running total", prompt: "Running total of orders.amount ordered by order_date.", answer: "SELECT id, amount, SUM(amount) OVER (ORDER BY order_date) FROM orders;", expectedRows: 10, hint: "Window SUM.", solution: "SELECT id, amount, SUM(amount) OVER (ORDER BY order_date) AS running_total FROM orders;" }),
  q("sql", 21, "advanced", { type: "code", title: "CTE for top customer", prompt: "Using a CTE, find the customer with highest delivered spend.", answer: "WITH spend AS (SELECT customer_id, SUM(amount) s FROM orders WHERE status='delivered' GROUP BY customer_id) SELECT c.name FROM customers c JOIN spend ON spend.customer_id=c.id ORDER BY s DESC LIMIT 1;", expectedRows: 1, hint: "WITH cte AS (...)", solution: "WITH spend AS (SELECT customer_id, SUM(amount) s FROM orders WHERE status='delivered' GROUP BY customer_id) SELECT c.name FROM customers c JOIN spend ON spend.customer_id=c.id ORDER BY s DESC LIMIT 1;" }),
  q("sql", 22, "advanced", { type: "code", title: "LAG month-over-month", prompt: "For each sale (by sale_date), show current amount and previous amount using LAG.", answer: "SELECT sale_date, amount, LAG(amount) OVER (ORDER BY sale_date) FROM sales;", expectedRows: 8, hint: "LAG().", solution: "SELECT sale_date, amount, LAG(amount) OVER (ORDER BY sale_date) AS prev FROM sales;" }),
  q("sql", 23, "advanced", { type: "code", title: "Dense rank", prompt: "DENSE_RANK employees by salary overall.", answer: "SELECT name, salary, DENSE_RANK() OVER (ORDER BY salary DESC) FROM employees;", expectedRows: 8, hint: "DENSE_RANK.", solution: "SELECT name, salary, DENSE_RANK() OVER (ORDER BY salary DESC) FROM employees;" }),
  q("sql", 24, "advanced", { type: "code", title: "Second highest salary", prompt: "Return the 2nd highest salary from employees.", answer: "SELECT DISTINCT salary FROM employees ORDER BY salary DESC LIMIT 1 OFFSET 1;", expectedRows: 1, hint: "OFFSET 1 after ordering desc.", solution: "SELECT DISTINCT salary FROM employees ORDER BY salary DESC LIMIT 1 OFFSET 1;" }),
  q("sql", 25, "advanced", { type: "code", title: "Self join for pairs", prompt: "Pairs of employees in same department (both names, no self-pairs).", answer: "SELECT a.name, b.name FROM employees a JOIN employees b ON a.dept_id=b.dept_id AND a.id<b.id;", expectedRows: 5, hint: "Join table to itself with id ordering.", solution: "SELECT a.name, b.name FROM employees a JOIN employees b ON a.dept_id = b.dept_id AND a.id < b.id;" }),
];

// ---------- PYTHON ----------
export const pythonQuestions = [
  // BEGINNER (9)
  q("python", 1, "beginner", { type: "code", title: "Print hello", prompt: "Print exactly: Hello, Data Hub!", starter: 'print(', expectedOutput: "Hello, Data Hub!", hint: "Use print()", solution: 'print("Hello, Data Hub!")' }),
  q("python", 2, "beginner", { type: "code", title: "Sum list", prompt: "Print the sum of [4, 8, 15, 16, 23, 42].", expectedOutput: "108", hint: "Use sum().", solution: "print(sum([4,8,15,16,23,42]))" }),
  q("python", 3, "beginner", { type: "code", title: "Uppercase", prompt: 'Print "data hub" in uppercase.', expectedOutput: "DATA HUB", hint: ".upper()", solution: 'print("data hub".upper())' }),
  q("python", 4, "beginner", { type: "code", title: "Length of list", prompt: "Print the length of the list [1,2,3,4,5,6,7].", expectedOutput: "7", hint: "len()", solution: "print(len([1,2,3,4,5,6,7]))" }),
  q("python", 5, "beginner", { type: "code", title: "For loop sum 1-10", prompt: "Print sum of numbers 1 through 10.", expectedOutput: "55", hint: "sum(range(1,11))", solution: "print(sum(range(1,11)))" }),
  q("python", 6, "beginner", { type: "code", title: "Even filter", prompt: "Print evens from [1..10] as a list.", expectedOutput: "[2, 4, 6, 8, 10]", hint: "List comprehension.", solution: "print([x for x in range(1,11) if x%2==0])" }),
  q("python", 7, "beginner", { type: "code", title: "Dictionary lookup", prompt: 'From d = {"a":1,"b":2,"c":3}, print value of key "b".', expectedOutput: "2", hint: "d[key]", solution: 'd={"a":1,"b":2,"c":3}\nprint(d["b"])' }),
  q("python", 8, "beginner", { type: "code", title: "String reverse", prompt: 'Print "hello" reversed.', expectedOutput: "olleh", hint: "Slice with [::-1].", solution: 'print("hello"[::-1])' }),
  q("python", 9, "beginner", { type: "mcq", title: "Which is a list?", prompt: "Which literal is a Python list?", options: ["(1,2,3)", "{1,2,3}", "[1,2,3]", "{'a':1}"], answer: "[1,2,3]", hint: "Square brackets.", solution: "[1,2,3] is a list." }),
  // INTERMEDIATE (9)
  q("python", 10, "intermediate", { type: "code", title: "Pandas import", prompt: "Import pandas as pd and print(pd.__name__).", expectedOutput: "pandas", hint: "Standard import.", solution: "import pandas as pd\nprint(pd.__name__)" }),
  q("python", 11, "intermediate", { type: "code", title: "DataFrame from dict", prompt: 'Create df=pd.DataFrame({"a":[1,2,3]}) and print(df["a"].sum()).', expectedOutput: "6", hint: "DataFrame constructor.", solution: 'import pandas as pd\ndf=pd.DataFrame({"a":[1,2,3]})\nprint(df["a"].sum())' }),
  q("python", 12, "intermediate", { type: "code", title: "Filter DataFrame", prompt: 'df=pd.DataFrame({"x":[10,20,30,40]}). Print count of rows where x>15.', expectedOutput: "3", hint: "df[df.x>15].shape[0]", solution: 'import pandas as pd\ndf=pd.DataFrame({"x":[10,20,30,40]})\nprint(len(df[df.x>15]))' }),
  q("python", 13, "intermediate", { type: "code", title: "GroupBy mean", prompt: 'df has cols region=["N","N","S"], amt=[10,20,50]. Print mean per region as dict.', expectedOutput: "{'N': 15.0, 'S': 50.0}", hint: "groupby().mean().to_dict()", solution: 'import pandas as pd\ndf=pd.DataFrame({"region":["N","N","S"],"amt":[10,20,50]})\nprint(df.groupby("region")["amt"].mean().to_dict())' }),
  q("python", 14, "intermediate", { type: "code", title: "NumPy mean", prompt: "Print numpy mean of [2,4,6,8].", expectedOutput: "5.0", hint: "np.mean.", solution: "import numpy as np\nprint(np.mean([2,4,6,8]))" }),
  q("python", 15, "intermediate", { type: "code", title: "List comprehension squares", prompt: "Print squares of 1..5 as a list.", expectedOutput: "[1, 4, 9, 16, 25]", hint: "[x*x for x in range(1,6)]", solution: "print([x*x for x in range(1,6)])" }),
  q("python", 16, "intermediate", { type: "code", title: "Remove duplicates", prompt: "Print sorted unique elements of [3,1,2,3,2,4] as a list.", expectedOutput: "[1, 2, 3, 4]", hint: "sorted(set(...))", solution: "print(sorted(set([3,1,2,3,2,4])))" }),
  q("python", 17, "intermediate", { type: "code", title: "Merge DataFrames", prompt: 'Left {"k":[1,2]} + right {"k":[1,2],"v":["a","b"]} merge on k. Print len.', expectedOutput: "2", hint: "pd.merge.", solution: 'import pandas as pd\nl=pd.DataFrame({"k":[1,2]}); r=pd.DataFrame({"k":[1,2],"v":["a","b"]})\nprint(len(pd.merge(l,r,on="k")))' }),
  q("python", 18, "intermediate", { type: "code", title: "Fillna", prompt: 'From pd.Series([1,None,3]).fillna(0).sum() print result as int.', expectedOutput: "4", hint: "fillna(0).", solution: 'import pandas as pd\nprint(int(pd.Series([1,None,3]).fillna(0).sum()))' }),
  // ADVANCED (7)
  q("python", 19, "advanced", { type: "code", title: "Pivot table", prompt: 'df with region=["N","N","S","S"], month=["Jan","Feb","Jan","Feb"], amt=[10,20,30,40]. Pivot region vs month sum. Print df.values.tolist().', expectedOutput: "[[10, 20], [30, 40]]", hint: "pivot_table.", solution: 'import pandas as pd\ndf=pd.DataFrame({"region":["N","N","S","S"],"month":["Jan","Feb","Jan","Feb"],"amt":[10,20,30,40]})\nprint(df.pivot_table(index="region",columns="month",values="amt").values.tolist())' }),
  q("python", 20, "advanced", { type: "code", title: "Linear regression", prompt: "Fit y=2x+1 on x=[1..5], y=[3,5,7,9,11] using numpy polyfit and print slope rounded to 2 decimals.", expectedOutput: "2.0", hint: "np.polyfit.", solution: "import numpy as np\nprint(round(np.polyfit([1,2,3,4,5],[3,5,7,9,11],1)[0],2))" }),
  q("python", 21, "advanced", { type: "code", title: "Value counts top", prompt: 'From pd.Series(["a","b","a","c","a","b"]).value_counts().idxmax() print result.', expectedOutput: "a", hint: "idxmax on value_counts.", solution: 'import pandas as pd\nprint(pd.Series(["a","b","a","c","a","b"]).value_counts().idxmax())' }),
  q("python", 22, "advanced", { type: "code", title: "Numpy where", prompt: "Given arr=np.array([5,15,25]), print np.where(arr>10, 1, 0).tolist().", expectedOutput: "[0, 1, 1]", hint: "np.where.", solution: "import numpy as np\narr=np.array([5,15,25])\nprint(np.where(arr>10,1,0).tolist())" }),
  q("python", 23, "advanced", { type: "code", title: "Apply lambda", prompt: 'df=pd.DataFrame({"x":[1,2,3]}). Add col y=x*10 with apply. Print df["y"].tolist().', expectedOutput: "[10, 20, 30]", hint: "df.assign or df['y']=df['x'].apply.", solution: 'import pandas as pd\ndf=pd.DataFrame({"x":[1,2,3]})\ndf["y"]=df["x"].apply(lambda v:v*10)\nprint(df["y"].tolist())' }),
  q("python", 24, "advanced", { type: "code", title: "Rolling mean", prompt: "pd.Series([1,2,3,4,5]).rolling(2).mean().dropna().tolist() -> print it.", expectedOutput: "[1.5, 2.5, 3.5, 4.5]", hint: "rolling window.", solution: "import pandas as pd\nprint(pd.Series([1,2,3,4,5]).rolling(2).mean().dropna().tolist())" }),
  q("python", 25, "advanced", { type: "code", title: "Correlation", prompt: 'df with a=[1,2,3,4], b=[2,4,6,8]. Print round(df.corr()["a"]["b"],2).', expectedOutput: "1.0", hint: "df.corr()", solution: 'import pandas as pd\ndf=pd.DataFrame({"a":[1,2,3,4],"b":[2,4,6,8]})\nprint(round(df.corr()["a"]["b"],2))' }),
];

// ---------- STATISTICS ----------
export const statsQuestions = [
  // BEGINNER (9)
  q("stats", 1, "beginner", { type: "mcq", title: "Mean of numbers", prompt: "Mean of [2, 4, 6, 8, 10]?", options: ["4", "5", "6", "8"], answer: "6", hint: "Sum / count.", solution: "(2+4+6+8+10)/5 = 6." }),
  q("stats", 2, "beginner", { type: "mcq", title: "Median definition", prompt: "The median is the…", options: ["Most frequent value", "Middle value when sorted", "Average", "Highest value"], answer: "Middle value when sorted", hint: "Order matters.", solution: "Median is the middle value in a sorted list." }),
  q("stats", 3, "beginner", { type: "mcq", title: "Mode", prompt: "Mode of [1,2,2,3,4,4,4,5]?", options: ["2", "3", "4", "5"], answer: "4", hint: "Most frequent.", solution: "4 appears three times." }),
  q("stats", 4, "beginner", { type: "mcq", title: "Range", prompt: "Range of [3,7,2,9,5]?", options: ["6", "7", "9", "12"], answer: "7", hint: "Max − Min.", solution: "9 − 2 = 7." }),
  q("stats", 5, "beginner", { type: "mcq", title: "Probability basics", prompt: "Prob of rolling an even on a fair six-sided die?", options: ["1/3", "1/2", "2/3", "3/4"], answer: "1/2", hint: "3 out of 6.", solution: "Evens: 2,4,6 → 3/6 = 1/2." }),
  q("stats", 6, "beginner", { type: "mcq", title: "Data type", prompt: "Which is a categorical variable?", options: ["Height", "Weight", "Blood type", "Age"], answer: "Blood type", hint: "Categorical vs numerical.", solution: "Blood type is a category." }),
  q("stats", 7, "beginner", { type: "mcq", title: "Bar vs Histogram", prompt: "Best chart for a continuous variable?", options: ["Bar", "Histogram", "Pie", "Scatter"], answer: "Histogram", hint: "Bins.", solution: "Histograms visualise distributions of continuous data." }),
  q("stats", 8, "beginner", { type: "mcq", title: "Percentage", prompt: "20% of 250?", options: ["25", "40", "50", "60"], answer: "50", hint: "0.2 × 250.", solution: "50." }),
  q("stats", 9, "beginner", { type: "mcq", title: "Sampling", prompt: "Simple random sampling means…", options: ["Every unit has equal chance", "Only extremes are picked", "Data is sorted first", "You pick the first N"], answer: "Every unit has equal chance", hint: "Fairness.", solution: "Equal chance for each unit." }),
  // INTERMEDIATE (9)
  q("stats", 10, "intermediate", { type: "mcq", title: "Std deviation feel", prompt: "Larger standard deviation means…", options: ["Data closer to mean", "More spread from the mean", "Bigger mean", "Fewer outliers"], answer: "More spread from the mean", hint: "Measure of spread.", solution: "Standard deviation quantifies spread." }),
  q("stats", 11, "intermediate", { type: "mcq", title: "Normal distribution 68%", prompt: "In a normal distribution, ~68% of data lies within…", options: ["±1 SD", "±2 SD", "±3 SD", "±0.5 SD"], answer: "±1 SD", hint: "Empirical rule.", solution: "68-95-99.7 rule." }),
  q("stats", 12, "intermediate", { type: "mcq", title: "Z-score", prompt: "Z-score of X=80 with mean=70, sd=5?", options: ["1", "1.5", "2", "2.5"], answer: "2", hint: "(X-μ)/σ.", solution: "(80-70)/5 = 2." }),
  q("stats", 13, "intermediate", { type: "mcq", title: "Correlation range", prompt: "Pearson correlation r lies in…", options: ["[0,1]", "[-1,1]", "[-∞,∞]", "[0,∞]"], answer: "[-1,1]", hint: "Bounded.", solution: "Between -1 and 1 inclusive." }),
  q("stats", 14, "intermediate", { type: "mcq", title: "Bayes intuition", prompt: "Bayes theorem updates…", options: ["Sample size", "Prior belief with new evidence", "Standard deviation", "Median"], answer: "Prior belief with new evidence", hint: "Posterior.", solution: "Posterior ∝ prior × likelihood." }),
  q("stats", 15, "intermediate", { type: "mcq", title: "CLT", prompt: "The Central Limit Theorem says the sampling distribution of the mean is…", options: ["Uniform", "Bimodal", "Approximately normal for large n", "Always exponential"], answer: "Approximately normal for large n", hint: "n → ∞.", solution: "Sampling mean tends to normality as n grows." }),
  q("stats", 16, "intermediate", { type: "mcq", title: "Confidence interval", prompt: "A 95% CI means…", options: ["The parameter is inside with 95% probability given data", "We are 95% confident the interval contains the true parameter", "95% of samples fall inside", "None of the above"], answer: "We are 95% confident the interval contains the true parameter", hint: "Frequentist.", solution: "Repeated intervals would contain the parameter 95% of the time." }),
  q("stats", 17, "intermediate", { type: "mcq", title: "Variance", prompt: "Variance is…", options: ["Square root of SD", "Square of SD", "Mean of data", "Median of data"], answer: "Square of SD", hint: "Var = σ².", solution: "Variance = SD²." }),
  q("stats", 18, "intermediate", { type: "mcq", title: "Skewness", prompt: "A right-skewed distribution has…", options: ["Mean < Median", "Mean > Median", "Mean = Median", "No mode"], answer: "Mean > Median", hint: "Tail pulls the mean.", solution: "Right skew → mean pulled to the right." }),
  // ADVANCED (7)
  q("stats", 19, "advanced", { type: "mcq", title: "P-value", prompt: "A p-value of 0.03 with α=0.05 means…", options: ["Fail to reject H0", "Reject H0", "Accept H0", "Cannot tell"], answer: "Reject H0", hint: "p < α.", solution: "0.03 < 0.05 → reject the null." }),
  q("stats", 20, "advanced", { type: "mcq", title: "Type I error", prompt: "Rejecting a true null hypothesis is called…", options: ["Type I", "Type II", "Type III", "Bias"], answer: "Type I", hint: "α.", solution: "Type I = false positive." }),
  q("stats", 21, "advanced", { type: "mcq", title: "T-test use case", prompt: "Two-sample t-test compares…", options: ["Two proportions", "Two means", "Two variances", "Two medians"], answer: "Two means", hint: "Means with unknown σ.", solution: "Two-sample t-test compares means." }),
  q("stats", 22, "advanced", { type: "mcq", title: "ANOVA", prompt: "One-way ANOVA compares…", options: ["Means of 2 groups", "Means of 3+ groups", "Variances of 2 groups", "Correlations"], answer: "Means of 3+ groups", hint: "Analysis of variance.", solution: "One-way ANOVA compares 3+ group means." }),
  q("stats", 23, "advanced", { type: "mcq", title: "Chi-square", prompt: "Chi-square test is used for…", options: ["Continuous vs continuous", "Categorical vs categorical (independence)", "Time series forecasting", "Regression fit"], answer: "Categorical vs categorical (independence)", hint: "Contingency tables.", solution: "Chi-square tests independence in categorical data." }),
  q("stats", 24, "advanced", { type: "mcq", title: "R-squared", prompt: "In linear regression, R² measures…", options: ["Slope", "Intercept", "Proportion of variance explained", "Residual sum"], answer: "Proportion of variance explained", hint: "Goodness of fit.", solution: "R² is the fraction of variance explained by the model." }),
  q("stats", 25, "advanced", { type: "mcq", title: "Logistic regression output", prompt: "Logistic regression predicts…", options: ["A continuous value", "A probability between 0 and 1", "A residual", "A z-score"], answer: "A probability between 0 and 1", hint: "Sigmoid.", solution: "Outputs a probability via sigmoid." }),
];

// ---------- POWER BI ----------
export const powerbiQuestions = [
  // BEGINNER (9)
  q("powerbi", 1, "beginner", { type: "mcq", title: "What is Power BI?", prompt: "Power BI is primarily used for…", options: ["Version control", "Business intelligence & reporting", "Cloud storage", "3D rendering"], answer: "Business intelligence & reporting", hint: "BI.", solution: "Power BI is a BI/reporting suite by Microsoft." }),
  q("powerbi", 2, "beginner", { type: "mcq", title: "Data connectors", prompt: "Which is NOT a native Power BI connector?", options: ["Excel", "SQL Server", "MongoDB Atlas", "Web page"], answer: "MongoDB Atlas", hint: "Native connectors.", solution: "MongoDB Atlas isn't native; needs 3rd-party." }),
  q("powerbi", 3, "beginner", { type: "mcq", title: "Slicer purpose", prompt: "A slicer is used to…", options: ["Filter visuals", "Format text", "Create measures", "Publish reports"], answer: "Filter visuals", hint: "Filter component.", solution: "Slicers filter connected visuals." }),
  q("powerbi", 4, "beginner", { type: "mcq", title: "Card visual", prompt: "A Card visual is best for…", options: ["Table listings", "A single KPI number", "Time series", "Maps"], answer: "A single KPI number", hint: "Big number.", solution: "Cards show one aggregated value." }),
  q("powerbi", 5, "beginner", { type: "mcq", title: "Where to publish?", prompt: "Reports are published to…", options: ["OneDrive", "Power BI Service", "Excel", "SharePoint only"], answer: "Power BI Service", hint: "app.powerbi.com.", solution: "Publish to Power BI Service (app.powerbi.com)." }),
  q("powerbi", 6, "beginner", { type: "mcq", title: "Query editor", prompt: "The Power Query Editor is used for…", options: ["Writing DAX", "Transforming source data", "Publishing", "Sharing"], answer: "Transforming source data", hint: "ETL.", solution: "Power Query is the ETL layer." }),
  q("powerbi", 7, "beginner", { type: "mcq", title: "Which is a visual?", prompt: "Which of these is a Power BI visual?", options: ["Card", "Trigger", "Flow", "Blob"], answer: "Card", hint: "See visuals pane.", solution: "Card is a built-in visual." }),
  q("powerbi", 8, "beginner", { type: "mcq", title: "File extension", prompt: "Power BI Desktop file extension is…", options: [".xlsx", ".pbix", ".rdl", ".pptx"], answer: ".pbix", hint: "Native format.", solution: ".pbix." }),
  q("powerbi", 9, "beginner", { type: "mcq", title: "Refresh data", prompt: "You updated the source Excel. To refresh in Power BI you…", options: ["Republish visuals manually", "Click Refresh in Home tab", "Delete visuals", "Reinstall"], answer: "Click Refresh in Home tab", hint: "Home > Refresh.", solution: "Home > Refresh re-imports data." }),
  // INTERMEDIATE (9)
  q("powerbi", 10, "intermediate", { type: "mcq", title: "DAX SUM vs SUMX", prompt: "SUMX differs from SUM because…", options: ["It's slower always", "It evaluates an expression row by row", "It only works on measures", "It ignores filters"], answer: "It evaluates an expression row by row", hint: "Iterator function.", solution: "SUMX iterates a table then sums the result." }),
  q("powerbi", 11, "intermediate", { type: "mcq", title: "Calculated column vs measure", prompt: "Measures are computed…", options: ["At import time", "At query time based on context", "Only in Power Query", "Only in visuals"], answer: "At query time based on context", hint: "Filter context.", solution: "Measures respond to the current filter context." }),
  q("powerbi", 12, "intermediate", { type: "mcq", title: "Relationships", prompt: "The recommended star schema puts facts in the…", options: ["Center connected to dimensions", "Outer edge", "In Power Query only", "In measures"], answer: "Center connected to dimensions", hint: "Star.", solution: "Fact table connects to surrounding dimensions." }),
  q("powerbi", 13, "intermediate", { type: "mcq", title: "Time intelligence YTD", prompt: "Which DAX function returns Year-to-Date?", options: ["DATESYTD", "TOTALYTD", "YEARTODATE", "YTD"], answer: "TOTALYTD", hint: "TOTALYTD(expression, dates).", solution: "TOTALYTD is the wrapper for YTD totals." }),
  q("powerbi", 14, "intermediate", { type: "mcq", title: "CALCULATE", prompt: "CALCULATE is used to…", options: ["Change filter context", "Only format visuals", "Only compute averages", "Publish reports"], answer: "Change filter context", hint: "Powerful DAX.", solution: "CALCULATE modifies filter context for its expression." }),
  q("powerbi", 15, "intermediate", { type: "mcq", title: "Drill-through", prompt: "Drill-through pages allow you to…", options: ["Jump to detail filtered by selected item", "Show a summary", "Remove filters", "Delete pages"], answer: "Jump to detail filtered by selected item", hint: "Navigation.", solution: "Right-click → Drill-through to a detail page." }),
  q("powerbi", 16, "intermediate", { type: "mcq", title: "Bookmark", prompt: "Bookmarks store…", options: ["A snapshot of report state (filters, visuals visibility)", "Only slicer selections", "A copy of data", "A DAX formula"], answer: "A snapshot of report state (filters, visuals visibility)", hint: "State capture.", solution: "Bookmarks capture the state of a page." }),
  q("powerbi", 17, "intermediate", { type: "mcq", title: "Cardinality", prompt: "In a star schema, dim-fact relationship is typically…", options: ["Many-to-many", "One-to-many (Dim→Fact)", "One-to-one", "Zero-to-many"], answer: "One-to-many (Dim→Fact)", hint: "Standard.", solution: "Dimensions one-to-many fact." }),
  q("powerbi", 18, "intermediate", { type: "mcq", title: "Query folding", prompt: "Query folding in Power Query…", options: ["Executes M steps at the source", "Only works in DAX", "Is not real", "Slows down refresh"], answer: "Executes M steps at the source", hint: "Push down.", solution: "Steps are pushed to source (e.g. SQL) as native queries." }),
  // ADVANCED (7)
  q("powerbi", 19, "advanced", { type: "mcq", title: "RANKX behavior", prompt: "RANKX ranks items in…", options: ["A table by expression", "Only visuals", "Only calendar tables", "The filter pane"], answer: "A table by expression", hint: "Second arg is expr.", solution: "RANKX(table, expression, [value], [order], [ties])." }),
  q("powerbi", 20, "advanced", { type: "mcq", title: "ALLSELECTED", prompt: "ALLSELECTED preserves…", options: ["No filters", "Filters from outside the visual (page, slicer)", "Only date filters", "Everything"], answer: "Filters from outside the visual (page, slicer)", hint: "Outer filters kept.", solution: "ALLSELECTED preserves outer filter context." }),
  q("powerbi", 21, "advanced", { type: "mcq", title: "RLS setup", prompt: "Row Level Security is defined in…", options: ["Power Query", "Modeling > Manage Roles", "Report view", "Home > Refresh"], answer: "Modeling > Manage Roles", hint: "Roles pane.", solution: "Manage Roles under Modeling tab." }),
  q("powerbi", 22, "advanced", { type: "mcq", title: "DirectQuery", prompt: "DirectQuery mode…", options: ["Caches all data locally", "Sends live queries to source per visual", "Only works with Excel", "Ignores relationships"], answer: "Sends live queries to source per visual", hint: "Live.", solution: "DirectQuery sends queries live to the source." }),
  q("powerbi", 23, "advanced", { type: "mcq", title: "Incremental refresh", prompt: "Incremental refresh requires…", options: ["Star schema", "A date column and defined range parameters", "Premium capacity only", "No requirements"], answer: "A date column and defined range parameters", hint: "RangeStart, RangeEnd.", solution: "Configured using RangeStart / RangeEnd parameters." }),
  q("powerbi", 24, "advanced", { type: "mcq", title: "Aggregations", prompt: "Aggregation tables improve performance by…", options: ["Storing pre-aggregated data alongside detail", "Deleting data", "Filtering visuals", "Refreshing faster"], answer: "Storing pre-aggregated data alongside detail", hint: "Cache.", solution: "Aggregation tables serve high-level queries fast." }),
  q("powerbi", 25, "advanced", { type: "mcq", title: "Tabular Editor", prompt: "Tabular Editor is used to…", options: ["Design visuals", "Bulk-edit measures and metadata", "Publish reports", "Do OCR"], answer: "Bulk-edit measures and metadata", hint: "3rd party power tool.", solution: "Tabular Editor speeds up modeling and measure creation." }),
];

// Master accessor
export const QUESTIONS = {
  excel: excelQuestions,
  sql: sqlQuestions,
  python: pythonQuestions,
  stats: statsQuestions,
  powerbi: powerbiQuestions,
};
